In [2]:
import numpy as np

data = [1,2,4]
da = [1,2,4,7.9,{1,2,3}]
a = np.array(data)
b = np.array(da)
print(a)
b[1] = b[1] + "apple"
print(b)
print(type(b))

[1 2 4]


TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [6]:
a = np.zeros(5)
b = np.arrange(1,2,5)
print(a)
print(b)

AttributeError: module 'numpy' has no attribute 'arrange'

In [8]:
data = np.linspace(1,10,6, endpoint=True)
print(data)

[ 1.   2.8  4.6  6.4  8.2 10. ]


In [17]:
q = [1,8,5,4]
da = np.array(q)
print(da)
da[1] = 10
print(da)

[1 8 5 4]
[ 1 10  5  4]


In [1]:
a = [1,2,3,4,5,6,7,8,9,10]

v = np.array(a)
ev = v[v % 2 == 0]
print(ev)

NameError: name 'np' is not defined

In [ ]:
# boolean masks 
arr1 = np.array([1,3,5,6,9,10])
check = arr1 > 5
print(check)

[False False False  True  True  True]


In [7]:
num = np.array([1,2,3,4,5,6,7,8,9,10])
check = num % 2 == 0
print(check)

[False  True False  True False  True False  True False  True]


In [14]:
arr1 = np.array([1,2,3,4,5])

sel = arr1[[0,2,3]]
print(sel)

arr2 = np.array([1,2,5,6,8,9,10,14,17])
data= arr2[1:9:4]
print(data)

[1 3 4]
[2 9]


In [29]:
arr = np.array([5,10,15,20,25,30,35,40,45,50])
a = arr[1::3]
print(a)
b = arr[-4:]
print(b)
print(arr[-1:-5:-1])




[10 25 40]
[35 40 45 50]
[50 45 40 35]


In [ ]:
#2 dimension array
d2 = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print(type(d2))
print(d2)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# 3 dimnension array
d3 = np.array(
    [  
       [[1,2,3],[4,5,6]],
       [[8,9,0],[3,4,5]],
       [[222,8,9],[6,7,8]]
    ]
)
data = d3[2,0,0]
a = d3[:,1,:]
print(data)
print(a)

222


In [8]:
a = np.arange(1,11)
square = a.__pow__(2)
print(square)


[  1   4   9  16  25  36  49  64  81 100]


In [21]:
a = np.array([1,2,3,4,5,6,7,8])
print(a)

result = np.reshape(a, (2,2,2))
print(result)

[1 2 3 4 5 6 7 8]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [25]:
a = [
    [1,5,3],
    [5,2,7]
]
arr = np.array(a)
m = np.mean(a)
arr[arr > m] = 0
print(arr)
 


[[1 0 3]
 [0 2 0]]
